name: Test stuff

on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        default: true
      force:
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Only create an archive containing the release instead of publishing it on GitHub"
        type: boolean
        required: false
        default: false
      force:
        description: "Allow overwriting an existing release, or making a release with an incorrect date"
        type: boolean
        required: false
        default: false

permissions: write-all

jobs:
  release:
    name: "Release the GAP package"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: Test
        shell: bash
        run: |
          ls -a $RUNNER_TEMP

      - name: "Setup GAP"
        uses: gap-actions/setup-gap@v3

      - name: "Update GitHub Pages"
        uses: stertooy/update-gh-pages@v6_compat
        if: ${{ !inputs.dry-run }}
